### ISSUE TITLE
segfault when crashing into telephone booths

### ISSUE THREAD

**Issue by madebr** [dethrace-labs/dethrace#134]
Using current master 44df22a37561307d47f4a59dd8b2ed03c27713aa and using [Carmageddon Demo](https://rr2000.cwaboard.co.uk/R4/PC/carmdemo.zip) (I haven't tested other versions).

Start a new race, and take the street on your left.
Accelerate on the sidewalk and crash with full speed into the telephone booths (such that you destroy multiple in one hit).
As a result, the game segfaults.
This problem can be reliably reproduced.

backtrace:
```
#0  0x0000000000449109 in DamageSystems (pCar=0x23aa238, pImpact_point=0x7fffffffd6f8, pEnergy_vector=0x7fffffffd710, pWas_hitting_a_car=1) at /home/maarten/programming/dethrace/src/DETHRACE/common/crush.c:617
#1  0x000000000042b098 in CrushAndDamageCar (c=0x23aa238, pPosition=0x7fffffffd818, pForce_car_space=0x7fffffffd830, car2=0x66f030 <gProgram_state+176>) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:3139
#2  0x000000000043e8b8 in DoCollide (car1=0x66f030 <gProgram_state+176>, car2=0x23aa238, r=0x7fffffffdaa0, n=0x7fffffffd9e0, k=3, pPass=0, mat1_to_mat2=0x7fffffffdc20) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:6516
#3  0x000000000043885c in CollideTwoCars (car1=0x66f030 <gProgram_state+176>, car2=0x23aa238, pPass=0) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:6001
#4  0x00000000004374db in CollideTwoCarsRepeatedly (car1=0x66f030 <gProgram_state+176>, car2=0x23aa238, dt=0.0399999991) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:5791
#5  0x00000000004370b3 in CollideTwoCarsWithWalls (car1=0x66f030 <gProgram_state+176>, car2=0x23aa238, dt=0.0399999991) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:5720
#6  0x0000000000436cbb in CrashCarsTogetherSinglePass (dt=0.0399999991, pPass=0, collide_list=0x7fffffffdf10) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:5645
#7  0x0000000000436126 in CrashCarsTogether (dt=0.0399999991) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:5430
#8  0x000000000041d474 in ApplyPhysicsToCars (last_frame_time=14015, pTime_difference=17) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:1185
#9  0x000000000048017b in MainGameLoop () at /home/maarten/programming/dethrace/src/DETHRACE/common/mainloop.c:556
#10 0x0000000000480856 in DoRace () at /home/maarten/programming/dethrace/src/DETHRACE/common/mainloop.c:722
#11 0x00000000004ca9b3 in DoGame () at /home/maarten/programming/dethrace/src/DETHRACE/common/structur.c:538
#12 0x00000000004cacfe in DoProgram () at /home/maarten/programming/dethrace/src/DETHRACE/common/structur.c:645
#13 0x000000000047e84e in GameMain (pArgc=1, pArgv=0x7fffffffe478) at /home/maarten/programming/dethrace/src/DETHRACE/common/main.c:105
#14 0x00000000004e6891 in original_main (pArgc=1, pArgv=0x7fffffffe478) at /home/maarten/programming/dethrace/src/DETHRACE/pc-dos/dossys.c:665
#15 0x00000000004e744d in main (argc=1, argv=0x7fffffffe478) at /home/maarten/programming/dethrace/src/DETHRACE/main.c:28
#16 0x00007ffff7a8eb75 in __libc_start_main () from /lib64/libc.so.6
#17 0x0000000000403a7e in _start ()
```

<details>

<summary>Full backtrace</summary>

```
#0  0x0000000000449109 in DamageSystems (pCar=0x23aa238, pImpact_point=0x7fffffffd6f8, pEnergy_vector=0x7fffffffd710, pWas_hitting_a_car=1) at /home/maarten/programming/dethrace/src/DETHRACE/common/crush.c:617
        i = 0
        j = 37397048
        result = 0
        crushed_car_bounds = {min = {v = {-0.179000005, 2.80259693e-45, 9.45338365e-39}}, max = {v = {0, 0.199999988, 0.485000014}}}
        proportion_x = 9.45338365e-39
        proportion_y = 4.59163468e-41
        proportion_z = -nan(0x7fd6a0)
        energy_magnitude = 4.59163468e-41
        pure_energy_magnitude = 0.667987943
        x = -nan(0x7fd670)
        y = 0.0450654812
        z = -0.303226233
        x1 = 0.111596979
        x2 = 0.246403039
        y1 = 0.0833626091
        y2 = 0.0566373765
        z1 = 0.0387737751
        z2 = 0.798226237
        distance = <optimized out>
        impact_location = 1019175660
        the_program = 0x66faa8 <gProgram_state+2856>
        the_clause = 0x3e4f40483c8381a3
        the_condition = 0x398a11e53e82b27d
        the_effect = 0x132f578
        modified_location = <optimized out>
        __FUNCTION__ = {68 'D', 97 'a', 109 'm', 97 'a', 103 'g', 101 'e', 83 'S', 121 'y', 115 's', 116 't', 101 'e', 109 'm', 115 's', 0 '\000'}
#1  0x000000000042b098 in CrushAndDamageCar (c=0x23aa238, pPosition=0x7fffffffd818, pForce_car_space=0x7fffffffd830, car2=0x66f030 <gProgram_state+176>) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:3139
        force = {v = {-0.036887493, -0.00032057325, -0.666968584}}
        force2 = {v = {0.164874852, 0.7263183, 1.37680686}}
        position = {v = {-0.0130171003, 0.221174806, 0.0310014524}}
        pos_w = {v = {-81.9094696, -3.1353929, 42.7735672}}
        car_to_cam = {v = {1.69721222, -0.411868334, -0.100193024}}
        force_for_bodywork = {v = {-0.0553312376, -0.00048085989, -1.00045288}}
        ts = 0.446207911
        i = 32767
        m = {m = {{0.0514661185, -0.0590094626, 0.996929824}, {-0.0132862106, 0.998123825, 0.0597660691}, {-0.998586416, -0.016321376, 0.0505855568}, {-82.2168808, -3.2875762, 42.8480415}}}
        fudge_multiplier = 1
        __FUNCTION__ = {67 'C', 114 'r', 117 'u', 115 's', 104 'h', 65 'A', 110 'n', 100 'd', 68 'D', 97 'a', 109 'm', 97 'a', 103 'g', 101 'e', 67 'C', 97 'a', 114 'r', 0 '\000'}
#2  0x000000000043e8b8 in DoCollide (car1=0x66f030 <gProgram_state+176>, car2=0x23aa238, r=0x7fffffffdaa0, n=0x7fffffffd9e0, k=3, pPass=0, mat1_to_mat2=0x7fffffffdc20) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:6516
        mat1 = 0xe6594c
        mat2 = 0x1f74efc
        oldmat1 = 0x66f074 <gProgram_state+244>
        oldmat2 = 0x23aa27c
        M = {m = {{9.81222248, 1.15522575, 9.85636902, 9.85636902}, {1.15522599, 8.75958157, 1.15522575, 1.15522575}, {9.85636806, 1.15522599, 8.75958157, 8.75958157}, {9.85636806, 2.55331779, 1.15522599, 8.75958157}}}
        tau1 = {{v = {-0.499998331, 4.59317207, -0.67253989}}, {v = {-0.57008481, -1.64521646, 0.268016428}}, {v = {-0.0240289401, -0.0693454817, 0.0112968292}}, {v = {-0.0240289401, -0.0693454817, 0.0112968292}}, {v = {-12.8953791, -52.5418282, 0.546638668}}, {v = {-12.0929012, 57.4041519, 0.512620449}}, {v = {-0.509712934, 2.4195714, 0.0216068309}}, {v = {-0.509712934, 2.4195714, 0.0216068309}}}
        a = {v = {76.8809509, 0.00412325561, -3.0478704}}
        norm = {v = {-0.0257779807, -1.86264515e-08, -0.499335021}}
        f1 = {v = {0.0558813512, 0.805894077, 44.5260773}}
        f2 = {v = {-1.22958314, -0.0106857754, -22.2322865}}
        pos1 = {v = {-0.465080917, 0.989202023, -2.16126108}}
        pos2 = {v = {-0.0898179933, 1.52610624, 0.213910028}}
        max_friction = {v = {-0.163219616, -0.0213698912, 0.00929501187}}
        tv = {v = {22.2322865, -0.0106857754, -1.22958314}}
        tv2 = {v = {-0.0816098079, -0.0106849456, 0.00464750594}}
        tau2 = 0x7fffffffd890
        torque1 = {v = {-1.07008314, 2.94795561, -0.404523462}}
        torque2 = {v = {-24.9882812, 4.86232376, 1.05925918}}
        f = {20.8081722, 23.724926, 0, 0}
        d = {76.8284302, 76.9556961, 76.9556961, 76.9556961}
        ts = 11.862463
        tforce = 44.5330963
        i = 2
        j = 4
        car1_point = -1
        car2_point = -1
        plane = -1101331534
        move_car1 = 1
        move_car2 = 1
        a2 = {v = {0, 0, 0}}
        f12 = {v = {0, 0, 0}}
        f22 = {v = {0, 0, 0}}
        point_vel1 = {v = {0.975958586, -1.18722439, -76.9333649}}
        point_vel2 = {v = {0, -0, 0}}
        fudge_multiplier = <optimized out>
        factor = 3
        need_to_fudge = 0
        __FUNCTION__ = {68 'D', 111 'o', 67 'C', 111 'o', 108 'l', 108 'l', 105 'i', 100 'd', 101 'e', 0 '\000'}
#3  0x000000000043885c in CollideTwoCars (car1=0x66f030 <gProgram_state+176>, car2=0x23aa238, pPass=0) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:6001
        k = 5
        old_k = 1
        i = 5
        j = 5
        dist = <optimized out>
        ts = <optimized out>
        new_car1_bnds = {min = {v = {-1.23510003, 0.342904389, -5.51359224}}, max = {v = {1.29455948, 1.38, 3.34650016}}}
        new_car2_bnds = {min = {v = {-0.517500043, 0.0689999983, -0.2139}}, max = {v = {0.517500043, 1.98030007, 0.2139}}}
        bnds = {min = {v = {-0.895759881, 0.0180718265, -3.14135981}}, max = {v = {0.270864546, 1.99332774, -2.63061333}}}
        mat1 = 0xe6594c
        mat2 = 0x1f74efc
        oldmat1 = 0x66f074 <gProgram_state+244>
        oldmat2 = 0x23aa27c
        inv_mat1 = {m = {{0.0562773831, -0.0101411091, -0.998363733}, {-0.0714561865, 0.997343063, -0.0141587444}, {0.995854795, 0.0721361041, 0.0554032326}, {-264.162415, -4.41456604, -579.993835}}}
        inv_mat2 = {m = {{0, 0, -1}, {0, 1, 0}, {1, 0, 0}, {-295.25412, 22.6395721, -564.444031}}}
        inv_oldmat1 = {m = {{0.0514661185, -0.0132862106, -0.998586416}, {-0.0590094626, 0.998123825, -0.016321376}, {0.996929824, 0.0597660691, 0.0505855568}, {-266.885803, -2.56543255, -581.820496}}}
        inv_oldmat2 = {m = {{0, 0, -1}, {0, 1, 0}, {1, 0, 0}, {-295.25412, 22.6395721, -564.444031}}}
        car2_to_car1 = {m = {{0.995854795, 0.0721361041, 0.0554032326}, {-0.0714561865, 0.997343063, -0.0141587444}, {-0.0562773831, 0.0101411091, 0.998363733}, {-0.279876709, 0.0285835266, 0.205200195}}}
        car1_to_car2 = {m = {{0.995854795, -0.0714561865, -0.0562773831}, {0.0721361041, 0.997343063, 0.0101411091}, {0.0554032326, -0.0141587444, 0.998363733}, {0.265289307, -0.0456008911, -0.22088623}}}
        old_car2_to_car1 = {m = {{0.996929824, 0.0597660691, 0.0505855568}, {-0.0590094626, 0.998123825, -0.016321376}, {-0.0514661185, 0.0132862106, 0.998586416}, {-0.251983643, -0.0170278549, -2.8692627}}}
        old_car1_to_car2 = {m = {{0.996929824, -0.0590094626, -0.0514661185}, {0.0597660691, 0.998123825, 0.0132862106}, {0.0505855568, -0.016321376, 0.998586416}, {0.397369385, -0.0447044373, 2.85247803}}}
        car1_to_old_car1 = {m = {{0.999910355, -0.0125515051, -0.00465570018}, {0.0125400312, 0.999917924, -0.00250219251}, {0.00468673185, 0.00244352384, 0.999986172}, {0.0265808105, -0.0496244431, -3.07562256}}}
        car2_to_old_car2 = {m = {{1, 0, 0}, {0, 1, 0}, {0, 0, 1}, {0, 0, 0}}}
        r = {{v = {0, 1.1730001, -1.06949997}}, {v = {0.397809863, 1.68098152, 0.2139}}, {v = {-0.872984469, 0.828000009, -3.11880016}}, {v = {-0.517496645, 1.39027131, 0.213918775}}, {v = {-0.803609133, -0.137999982, -3.11880016}}, {v = {-0.517496586, 0.421698242, 0.213918805}}, {v = {0.232404694, -0.137999982, -3.11880016}}, {v = {0.517503381, 0.346838474, 0.213918805}}, {v = {0.163032934, 0.828000009, -3.11880016}}, {v = {0.517503381, 1.31541169, 0.213918775}}, {v = {0.180118203, 1.38, -2.42880011}}, {v = {0.517503381, 1.31976163, -0.213881269}}, {v = {0.24948059, 0.414000005, -2.42880011}}, {v = {0.517503381, 0.351188451, -0.213881224}}, {v = {0, 0, 1}}, {v = {0, 0, 0}}}
        n = {{v = {0.00489113107, 0.0187917612, 0.99981153}}, {v = {-0.0515559614, -3.7252903e-08, -0.998670042}}, {v = {0.00489113107, 0.0187917612, 0.99981153}}, {v = {-0.0515559614, -3.7252903e-08, -0.998670042}}, {v = {0.00489113107, 0.0187917612, 0.99981153}}, {v = {-0.0515559614, -3.7252903e-08, -0.998670042}}, {v = {0.00489113107, 0.0187917612, 0.99981153}}, {v = {-0.0515559614, -3.7252903e-08, -0.998670042}}, {v = {0.00489113107, 0.0187917612, 0.99981153}}, {v = {-0.0515559614, -3.7252903e-08, -0.998670042}}, {v = {0.00489112735, 0.0187917687, 0.99981153}}, {v = {-0.0515559614, -4.47034836e-08, -0.998670042}}, {v = {0.00489112735, 0.0187917687, 0.99981153}}, {v = {-0.0515559614, -4.47034836e-08, -0.998670042}}, {v = {1.43492963e-39, 0, 5.73971851e-42}}, {v = {3.58732407e-42, 5.60519386e-43, 1.40129846e-45}}}
        sep = {v = {0, 0, 0}}
        tv = {v = {0, 0, 0}}
        add_point = 0
        oldr1 = {v = {0, 1.1730001, -1.06949997}}
        oldr2 = {v = {0.397809863, 1.68098152, 0.2139}}
        oldn1 = {v = {-0.0514661185, 0.0132862106, 0.998586416}}
        oldn2 = {v = {0, 0, -1}}
        is_old_point_available = 0
        __FUNCTION__ = {67 'C', 111 'o', 108 'l', 108 'l', 105 'i', 100 'd', 101 'e', 84 'T', 119 'w', 111 'o', 67 'C', 97 'a', 114 'r', 115 's', 0 '\000'}
#4  0x00000000004374db in CollideTwoCarsRepeatedly (car1=0x66f030 <gProgram_state+176>, car2=0x23aa238, dt=0.0399999991) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:5791
        l = 0
        collide = 0
        ts = <optimized out>
        __FUNCTION__ = {67 'C', 111 'o', 108 'l', 108 'l', 105 'i', 100 'd', 101 'e', 84 'T', 119 'w', 111 'o', 67 'C', 97 'a', 114 'r', 115 's', 82 'R', 101 'e', 112 'p', 101 'e', 97 'a', 116 't', 101 'e', 100 'd', 108 'l', 121 'y', 0 '\000'}
#5  0x00000000004370b3 in CollideTwoCarsWithWalls (car1=0x66f030 <gProgram_state+176>, car2=0x23aa238, dt=0.0399999991) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:5720
        mom1 = {v = {9.45428048e-39, 0, -nan(0x7fde80)}}
        mom2 = {v = {4.59163468e-41, 1.37123938e-37, 0}}
        l = 0
        m = 0
        n = 4419591
        p = 0
        im1 = 0
        im2 = 0
        __FUNCTION__ = {67 'C', 111 'o', 108 'l', 108 'l', 105 'i', 100 'd', 101 'e', 84 'T', 119 'w', 111 'o', 67 'C', 97 'a', 114 'r', 115 's', 87 'W', 105 'i', 116 't', 104 'h', 87 'W', 97 'a', 108 'l', 108 'l', 115 's', 0 '\000'}
#6  0x0000000000436cbb in CrashCarsTogetherSinglePass (dt=0.0399999991, pPass=0, collide_list=0x7fffffffdf10) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:5645
        i = 0
        j = 1
        l = <optimized out>
        m = <optimized out>
        n = <optimized out>
        collided = 0
        k = -1159844154
        ref1 = <optimized out>
        ref2 = <optimized out>
        c1im = 1049014165
        c2im = 1002772940
        car_1 = 0x66f030 <gProgram_state+176>
        car_2 = 0x23aa238
        car_3 = 0x33fa4e36d
        car_in_middle = 0x3e86b9523ebf2cb7
        car_on_wall = 0x66f218 <gProgram_state+664>
        __FUNCTION__ = {67 'C', 114 'r', 97 'a', 115 's', 104 'h', 67 'C', 97 'a', 114 'r', 115 's', 84 'T', 111 'o', 103 'g', 101 'e', 116 't', 104 'h', 101 'e', 114 'r', 83 'S', 105 'i', 110 'n', 103 'g', 108 'l', 101 'e', 80 'P', 97 'a', 115 's', 115 's', 0 '\000'}
#7  0x0000000000436126 in CrashCarsTogether (dt=0.0399999991) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:5430
        pass = 0
        k = 1
        i = 2
        collide_list = {{ref = 0, car = 0x0}, {ref = 0, car = 0x0}, {ref = -1045280704, car = 0xc1b111a5c40d88f2}, {ref = 1133733276, car = 0x439438edc1b1d9c6}, {ref = 1065344811, car = 0x3cbb4382bcb21f1c}, {ref = 1065348478, car = 0x3bc2b2ed3cb348ea}, {ref = 1065348904, car = 0xbfab82c0bcd4a1c0}, {ref = 1065351712, car = 0xbc4da4d43b999328}, {ref = 1065351839, car = 0xbb23fbd3bb988ed8}, {ref = 1065352984, car = 0x3ee439003bc58400}, {ref = 1030128413, car = 0xbd92579fbf7f94c4}, {ref = 1065308640, car = 0x3d93bc183f7ef057}, {ref = 1029893760, car = 0xc2a81d39bf23c970}, {ref = 1028836899, car = 0xbc59ae683f7f36cb}, {ref = 1065321739, car = 0xbc85b468bf7fa35c}, {ref = 1028600525, car = 0x422b6465c05267a6}, {ref = 1030128413, car = 0xbc2626e53f7ef057}, {ref = 1065308640, car = 0x412d2010bf7f94c4}, {ref = 1033035392, car = 0xc04d64ccc2a2dcdc}, {ref = 1110081306, car = 0x422b50cbc05269c7}, {ref = 0, car = 0x66f030 <gProgram_state+176>}, {ref = -1102321915, car = 0x3e5548acbfd987b9}, {ref = 1048245652, car = 0x3b2023f93b99931e}, {ref = 1065352982, car = 0x66f030 <gProgram_state+176>}, {ref = -1095417987, car = 0x66f030 <gProgram_state+176>}, {ref = 3, car = 0x6677a0 <gFace_list__car+3648>}, {ref = -1083446473, car = 0x66f074 <gProgram_state+244>}, {ref = 6746192, car = 0x66f068 <gProgram_state+232>}, {ref = -7952, car = 0xe6594c}, {ref = 6746380, car = 0x1}, {ref = -7904, car = 0x41d9a6 <MoveAndCollideCar+566>}, {ref = 4209232, car = 0x66f030 <gProgram_state+176>}}
        __FUNCTION__ = {67 'C', 114 'r', 97 'a', 115 's', 104 'h', 67 'C', 97 'a', 114 'r', 115 's', 84 'T', 111 'o', 103 'g', 101 'e', 116 't', 104 'h', 101 'e', 114 'r', 0 '\000'}
#8  0x000000000041d474 in ApplyPhysicsToCars (last_frame_time=14015, pTime_difference=17) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:1185
        minus_k = {v = {4.59163468e-41, 6.03382724e-39, 0}}
        i = 1
        old_num_cars = 2
        step_number = 1
        dam_index = 2595153
        steering_locked = 0
        car = 0x66f030 <gProgram_state+176>
        car_info = 0x7fffffffe180
        non_car = 0x23aa238
        time_step = <optimized out>
        frame_end_time = 14032
        __FUNCTION__ = {65 'A', 112 'p', 112 'p', 108 'l', 121 'y', 80 'P', 104 'h', 121 'y', 115 's', 105 'i', 99 'c', 115 's', 84 'T', 111 'o', 67 'C', 97 'a', 114 'r', 115 's', 0 '\000'}
#9  0x000000000048017b in MainGameLoop () at /home/maarten/programming/dethrace/src/DETHRACE/common/mainloop.c:556
        camera_period = 17
        start_menu_time = 0
        frame_start_time = 2595153
        result = eRace_game_abandonned
        tried_to_allocate_AR = 1
        i = 32767
        bonus = 5137198
        __FUNCTION__ = {77 'M', 97 'a', 105 'i', 110 'n', 71 'G', 97 'a', 109 'm', 101 'e', 76 'L', 111 'o', 111 'o', 112 'p', 0 '\000'}
#10 0x0000000000480856 in DoRace () at /home/maarten/programming/dethrace/src/DETHRACE/common/mainloop.c:722
        result = eRace_game_abandonned
        __FUNCTION__ = {68 'D', 111 'o', 82 'R', 97 'a', 99 'c', 101 'e', 0 '\000'}
#11 0x00000000004ca9b3 in DoGame () at /home/maarten/programming/dethrace/src/DETHRACE/common/structur.c:538
        options_result = eSO_continue
        race_result = 32767
        second_select_race = 1
        first_summary_done = 30000
        i = 0
        __FUNCTION__ = {68 'D', 111 'o', 71 'G', 97 'a', 109 'm', 101 'e', 0 '\000'}
#12 0x00000000004cacfe in DoProgram () at /home/maarten/programming/dethrace/src/DETHRACE/common/structur.c:645
No locals.
#13 0x000000000047e84e in GameMain (pArgc=1, pArgv=0x7fffffffe478) at /home/maarten/programming/dethrace/src/DETHRACE/common/main.c:105
        CD_dir = {0 '\000', -29 '\343', -1 '\377', -1 '\377', -1 '\377', 127 '\177', 0 '\000', 0 '\000', 64 '@', -30 '\342', -1 '\377', -1 '\377', -1 '\377', 127 '\177', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', -34 '\336', -1 '\377', 94 '^', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 5 '\005', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', -32 '\340', -28 '\344', -66 '\276', -9 '\367', -1 '\377', 127 '\177', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 64 '@', 44 ',', 92 '\\', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', -32 '\340', -31 '\341', -1 '\377', -9 '\367', -1 '\377', 127 '\177', 0 '\000', 0 '\000', 32 ' ', -29 '\343', -1 '\377', -1 '\377', -1 '\377', 127 '\177', 0 '\000', 0 '\000', -19 '\355', 28 '\034', 79 'O', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 96 '`', -29 '\343', -1 '\377', -1 '\377', -1 '\377', 127 '\177', 0 '\000', 0 '\000', 123 '{', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 123 '{', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 2 '\002', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 96 '`', -29 '\343', -1 '\377', -1 '\377', -1 '\377', 127 '\177', 0 '\000', 0 '\000', -26 '\346', 31 '\037', 79 'O', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000'...}
#14 0x00000000004e6891 in original_main (pArgc=1, pArgv=0x7fffffffe478) at /home/maarten/programming/dethrace/src/DETHRACE/pc-dos/dossys.c:665
        arg = 6040640
        i = 1
        f = 0
#15 0x00000000004e744d in main (argc=1, argv=0x7fffffffe478) at /home/maarten/programming/dethrace/src/DETHRACE/main.c:28
No locals.
#16 0x00007ffff7a8eb75 in __libc_start_main () from /lib64/libc.so.6
No symbol table info available.
#17 0x0000000000403a7e in _start ()
No symbol table info available.
```

</details>

Extra info:

This is the crash site:
https://github.com/dethrace-labs/dethrace/blob/44df22a37561307d47f4a59dd8b2ed03c27713aa/src/DETHRACE/common/crush.c#L617-L617

It looks like `pCar->principal_car_actor` is not initialized at that point:
```
(gdb) print pCar->principal_car_actor
$1 = -1093404721
```

**Comment by dethrace-labs** [comment]
Fixed in #144
