### ISSUE TITLE
MassageOpponentPosition not implemented

### ISSUE THREAD

**Issue by plaes** [dethrace-labs/dethrace#138]
After running current main branch at normal difficulty, I end up calling unimplemented `MassageOpponentPosition` function:
```
#3  0x0000aaaaaab6b8a0 in MassageOpponentPosition (pOpponent_spec=0xaaaaaad9a980 <gProgram_state+9944>, pMassage_count=0) at DETHRACE/common/opponent.c:1639
#4  0x0000aaaaaab6c6e4 in RematerialiseOpponent (pOpponent_spec=0xaaaaaad9a980 <gProgram_state+9944>, pSpeed=7) at DETHRACE/common/opponent.c:1802
#5  0x0000aaaaaab6baf4 in RematerialiseOpponentOnNearestSection (pOpponent_spec=0xaaaaaad9a980 <gProgram_state+9944>, pSpeed=7) at DETHRACE/common/opponent.c:1693
#6  0x0000aaaaaab78a70 in FollowCheatyPath (pOpponent_spec=0xaaaaaad9a980 <gProgram_state+9944>) at DETHRACE/common/oppoproc.c:679
#7  0x0000aaaaaab7670c in ProcessFollowPath (pOpponent_spec=0xaaaaaad9a980 <gProgram_state+9944>, pCommand=ePOC_run, pPursuit_mode=0, pIgnore_end=0, pNever_struggle=0) at DETHRACE/common/oppoproc.c:209
#8  0x0000aaaaaab67518 in ProcessCompleteRace (pOpponent_spec=0xaaaaaad9a980 <gProgram_state+9944>, pCommand=ePOC_run) at DETHRACE/common/opponent.c:744
#9  0x0000aaaaaab648e8 in ProcessCurrentObjective (pOpponent_spec=0xaaaaaad9a980 <gProgram_state+9944>, pCommand=ePOC_run) at DETHRACE/common/opponent.c:105
#10 0x0000aaaaaab6ac7c in ProcessThisOpponent (pOpponent_spec=0xaaaaaad9a980 <gProgram_state+9944>) at DETHRACE/common/opponent.c:1482
#11 0x0000aaaaaab6e3b4 in MungeOpponents (pFrame_period=57) at DETHRACE/common/opponent.c:2144
#12 0x0000aaaaaab58a28 in MainGameLoop () at DETHRACE/common/mainloop.c:548
#13 0x0000aaaaaab5937c in DoRace () at DETHRACE/common/mainloop.c:722
#14 0x0000aaaaaabbe978 in DoGame () at DETHRACE/common/structur.c:538
#15 0x0000aaaaaabbedf8 in DoProgram () at DETHRACE/common/structur.c:645
#16 0x0000aaaaaab56a04 in GameMain (pArgc=1, pArgv=0xfffffffff018) at DETHRACE/common/main.c:105
#17 0x0000aaaaaabdda10 in original_main (pArgc=1, pArgv=0xfffffffff018) at DETHRACE/pc-dos/dossys.c:669
#18 0x0000aaaaaaac257c in main (argc=1, argv=0xfffffffff018) at DETHRACE/main.c:28
(gdb) up 3
#3  0x0000aaaaaab6b8a0 in MassageOpponentPosition (pOpponent_spec=0xaaaaaad9a980 <gProgram_state+9944>, pMassage_count=0) at DETHRACE/common/opponent.c:1639
1639        NOT_IMPLEMENTED();
(gdb) info locals
mat = <optimized out>
car_trans = <optimized out>
displacement = {v = {-3.24676375e-13, 6.12227299e-41, -nan(0x7fe7d8)}}
positive_y_vector = {v = {-3.24676375e-13, 6.12227299e-41, -nan(0x7fe7d8)}}
direction_v = {v = {-3.24676375e-13, 6.12227299e-41, -nan(0x7fe7d8)}}
__FUNCTION__ = "MassageOpponentPosition"
(gdb) info args
pOpponent_spec = 0xaaaaaad9a980 <gProgram_state+9944>
pMassage_count = 0
```

**Comment by dethrace-labs** [comment]
Fixed in #153
